@BASE_URL=http://localhost:3000


### n8n automation webhook
POST http://localhost:5678/webhook-test/fb755256-d121-4692-b56b-86c3cd2419f6
Content-Type: application/json

{
    "body":"Hello n8n"
}


### User registration
POST {{BASE_URL}}/api/users/
Content-Type: application/json

{
    "email":"testemail@gmail.com"
}

### User login
POST {{BASE_URL}}/api/users/testemail@gmail.com


### Delete User
DELETE {{BASE_URL}}/api/users/testemail@gmail.com


### Create a new task
POST {{BASE_URL}}/api/tasks
Content-Type: application/json

{
    "user_id": 22,
    "task_name": "Finish backend routes",
    "repository_branch": "main",
    "project_name": "NodeJS API",
    "task_description": "Implement all CRUD endpoints for tasks",
    "deadline": "2026-01-10T12:00:00Z"
}


### Get all tasks based on userId
GET {{BASE_URL}}/api/tasks/22


### Get single task by taskId ans userId

GET {{BASE_URL}}/api/tasks/2/3


### Update task
#taskId
PUT {{BASE_URL}}/api/tasks/18
Content-Type: application/json

{
    "task_name": "Finish backend routes updated",
    "repository_branch": "develop",
    "project_name": "NodeJS API",
    "status": "pending",
    "task_description": "Updated description for task",
    "deadline": "2026-01-12T18:00:00Z"
}


### Delete task
#taskId
DELETE {{BASE_URL}}/api/tasks/18
