@BASE_URL=http://localhost:3000
@N8N_WORKFLOW=https://primary-ar96-production.up.railway.app/webhook-test/714ec72e-d6fa-468a-8350-a0f755109e0f
@N8N_CHAT=https://primary-ar96-production.up.railway.app/webhook-test/ba83f501-df13-4e32-af6d-2cdeac981de9


### n8n automation webhook
POST {{N8N_WORKFLOW}}
Content-Type: application/json

{
    "use":"chat",
    "email":"skoro@gmail.com",
    "title":"Zlatan",
    "youtube_url":"https://www.youtube.com/watch?v=Npsg0UvEGIw"
}


### User registration
POST {{BASE_URL}}/api/users/
Content-Type: application/json

{
    "email":"testemail@gmail.com"
}

### User login
POST {{BASE_URL}}/api/users/testemail@gmail.com


### Delete User
DELETE {{BASE_URL}}/api/users/testemail@gmail.com


### Create a new task
POST {{BASE_URL}}/api/tasks
Content-Type: application/json

{
    "user_id":54,
    "email":"skoro.toni01@gmail.com",
    "title":"Zlatan",
    "youtube_url":"https://somevideo.dfsd",
    "notes":"Some notes"
}


### Get all tasks based on userId
GET {{BASE_URL}}/api/tasks/54


### Get single task by taskId

GET {{BASE_URL}}/api/tasks/7


### Update task
#taskId
PUT {{BASE_URL}}/api/tasks/1
Content-Type: application/json

{
    "title":"Something else",
    "notes":"Some other notes"
}


### Delete task
#taskId
DELETE {{BASE_URL}}/api/tasks/1
